package regex;

public enum Event {
	REBOOT, 
	_3G_CONNECTION, 
	RSIM, 
	FIRST_AUTH, 
	VSIM_AUTH_REQUEST, 
	SERVERS_AUTH_REQUEST, 
	ATMEL_AUTH_REQUEST, 
	SERVERS_AUTH_RESPONSE, 
	SERVERS_AUTH_ROUND_TRIP, 
	VSIM_AUTH_RESPONSE, 
	ATMEL_AUTH_RESPONSE, 
	ATMEL_AUTH_ROUND_TRIP, 
	_4G_CONNECTION,
	REBOOT_TO_4G,
	_3G_TO_4G,
	FIRST_AUTH_TO_4G, REBOOT_TO_3G, _3G_TO_RSIM, RSIM_TO_FIRST_AUTH
}
